# Default values for golinks.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/taliamax/golinks
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

golinks:
  enableProfiling: false
  logLevel: critical
  # Set this to true if you want the service to restart itself
  # when the configmap changes. While this is a fast operation,
  # it does not guarantee zero downtime. For high-traffic scenarios,
  # using `kubectl rollout restart` might be more appropriate.
  watchFileChanges: false

routes:
  google: https://google.com
  github: https://github.com
  golinks: https://github.com/taliamax/golinks

## @param commonLabels Add labels to all the deployed resources
##
commonLabels:
  app: golinks
## @param commonAnnotations Add annotations to all the deployed resources
##
commonAnnotations:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  annotations: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
