version: '3.9'

services:
  golinks:
    build:
      context: ..
      dockerfile: devstack/Dockerfile
      target: ${TARGET:-builder}
    image: ghcr.io/taliamax/golinks:${VERSION:-latest}
    ports:
      - "80:80"
    volumes:
      - ../:/app
    environment:
      - ROCKET_PORT=80
      - GOLINKS_PROFILING=1
      - ROCKET_LOG_LEVEL=normal
      - GOLINKS_ROUTES=/app/conf/routes.yaml
