version: '3.5'

services:
  parser:
    build:
      context: ..
      dockerfile: devstack/parser.dockerfile
    image: parser
    volumes:
      - "../nginx:/app/nginx"
      - "../data:/app/data"
  
  router:
    build:
      context: ..
      dockerfile: devstack/router.dockerfile
    image: router
    ports:
      - "80:80"
      - "443:443"
    network_mode: bridge
    volumes:
      - "../nginx:/etc/nginx"