version: '3.9'

services:
  golinks:
    build:
      context: ..
      dockerfile: devstack/Dockerfile
      target: ${TARGET:-build}
    image: ${REGISTRY}golinks:${VERSION:-latest}
    ports:
      - "80:80"
    volumes:
      - ../:/app
    env_file:
      - ../.env
