version: '3.5'

services:
  golinks:
    build:
      context: ..
      dockerfile: devstack/Dockerfile
    image: golinks
    ports:
      - "80:80"
    volumes:
      - ../confs:/app/confs
    env_file:
      - ../.env
