apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "golinks.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "golinks.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "golinks.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ROCKET_PORT
              value: "{{ .Values.service.port }}"
            - name: ROCKET_LOG_LEVEL
              value: "{{ .Values.golinks.logLevel }}"
            {{- if  .Values.golinks.enableProfiling }}
            - name: GOLINKS_PROFILING
              value: "1"
            {{- end }}
            {{- if .Values.golinks.watchFileChanges }}
            - name: GOLINKS_WATCH
              value: "1"
            {{- end }}
            - name: GOLINKS_ROUTES
              value: "/etc/golinks/routes.yaml"
          volumeMounts:
            - name: routes
              mountPath: /etc/golinks
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /healthcheck
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - /healthcheck
            initialDelaySeconds: 5
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: routes
          configMap:
            name: routes-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}