name: build

on:
  push:
    branches: [master]

env:
  registry: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the runner container
        uses: docker/build-push-action@v3
        with:
          file: devstack/Dockerfile
          push: true
          target: runner
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/{{ github.repository }}:latest
