name: nightly-scan

on:
  schedule:
    # 7 AM UTC every day
    - cron: "0 7 * * *"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install rust tool chain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Run the security scanner
        run: cargo audit

  sha-scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - prod
          - debug
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build the docker container
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --target ${{ matrix.target }} \
            --file devstack/Dockerfile \
            .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true

  registry-image-scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - latest
          - debug
    steps:
      - name: Pull the docker image to scan
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.tag }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.tag }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
